### ISSUE TITLE
proposal: adapt the API to be compatible with sqlite virtual tables

### ISSUE THREAD

**Issue by daqscott** [tglman/orientdb-c#1]
Hi there,
  I was referred to this project by Luca after submitting this post to the mailing list: http://groups.google.com/group/orient-database/browse_thread/thread/84797f409501bb0b

I would like to make the same suggestion to you as a possible add-on to the work you're doing here. The URL above describes the idea in more detail, but I'll give a quick synopsis. Sqlite has a "virtual table" interface (http://www.sqlite.org/vtab.html) which is a well documented api that, when implemented, makes sqlite facade to any data source behind it. 

The motivation behind doing this is that once completed, is that ANY programming language with a sqlite API (I can't think of many that don't have one) would be capable of accessing OrientDB (in addition to the sqlite cli). I think this would be a highly desirable thing for the project, and it would also be a natural fit as Orient actually has a sql interface. 

I lack the C skills to provide any useful help in such an effort, but I would be willing to help in any other capacity I can (testing, documentation, etc). 

What do you think?

**Comment by tglman** [comment]
to complex and not needed!

Won't fix!

cheers
