### ISSUE TITLE
Long commands > 2x START_BUFFER_SIZE cannot be supported

### ISSUE THREAD

**Issue by willmoss** [tglman/orientdb-c#7]
Any queries that are longer than 2 x START_BUFFER_SIZE will not be properly executed and the program will terminate with 
- glibc detected : realloc(): invalid next size: 0x0000000001782030 **
  ======= Backtrace: ========= ............................

This is due to a limit set in o_output_stream_byte_write_bytes() and o_output_stream_byte_buffer(),

In o_output_stream_byte_write_bytes(), the buffer will only expand to max of 2 x START_BUFFER_SIZE .

A fix is to increase this value, however code needs to be refactored so its supports any value.

o_output_stream_byte.c

```
void o_output_stream_byte_write_bytes(struct o_output_stream * stream, void *bytes, int nbytes)
{
...
      if (buff->cursor + nbytes >= buff->size)
    {
        buff->size = buff->size * 4;
    }
}
```

o_output_stream_byte.c

```
struct o_output_stream * o_output_stream_byte_buffer()
 {
...
      stream->size = START_BUFFER_SIZE;
...
 }
```

**Comment by tglman** [comment]
can you post here an example query or a snipped of code that can be include as test case ?

Tnks!

**Comment by willmoss** [comment]
Ok here's an example from a graph with vertex Address and edge Route 

create edge Route from (select from address where addr='183343338563374563228322331213043') to (select from address where addr='1833433385633456322832237831213043') set jid='l4184hg596403b9d638783cn57ox34c75c605f6356fbc91338530e9831q9a11', jvalue=100000000

**Comment by tglman** [comment]
fixed but leaved open until I'll implement a proper test

**Comment by tglman** [comment]
test implemented!
